---
development:
  cloud_name: dmnxkrezn
  api_key: '688296223434775'
  api_secret: QdrX8jyhIPWdC_E7pk96dnNI_0U
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dmnxkrezn
  api_key: '688296223434775'
  api_secret: QdrX8jyhIPWdC_E7pk96dnNI_0U
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dmnxkrezn
  api_key: '688296223434775'
  api_secret: QdrX8jyhIPWdC_E7pk96dnNI_0U
  enhance_image_tag: true
  static_file_support: false
